version: 8.1.2

logging:
  level:
    cn.crap: DEBUG
  pattern:
    console: "%boldMagenta(%d{yyyy-MM-dd HH:mm:ss}) [%p] %highlight(%C:%L) : %m %n"

spring:
  mvc:
    throw-exception-if-no-handler-found: false
    view:
      prefix: /
  resources:
    add-mappings: true
  session:
    store-type: none
  application:
    name: ferrari-service
  multipart:
    max-file-size: 300MB
    max-request-size: 500MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: hi_doctor
    url: jdbc:mysql://127.0.0.1:3000/hi_api?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  basepackage: cn.crap.mapper.mybatis
  xmlLocation: classpath:mapper/**/*.xml

swagger:
  basepackage: cn.crap.controller
  service:
    name: 管理服务
    description: 用户,角色,权限

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

### 站点配置
web:
  openRegister: true
  luceneSearchNeedLogin: false
  baidu:
  cacheTime: 3600
  loginInforTime: 7200
  canRepeatUrl: true
  fileSize: 2
  fileType: txt,doc,xls,xlsx,rar,zip,pdf,docx
  imageType: gif,jpg,jpeg,png,bmp,ico,webp

## 企业邮箱
mail:
  username: crap_cn@163.com
  host: smtp.163.com
  password: test20180401

## 第三方登录 GitHub
github:
  clientID: 198bcac070c454e23cf1
  clientSecret: 1dd69ad93c1e7f739deaf95fd1807e192300ea99

## 第三方登录 码云
git.oschina:
  clientID: 93b820393bddda5a24fdff8ac9d6ec08473934dd3735b48f843d57e21be3bf7b
  clientSecret: 7101c54ed31e5f2bf4a129c2f8d27c3373acf4848ad8550ef1af2e10735cdac8

## 阿里云oss存储
aliyun.oss:
  accessKeyId:
  accessKeySecret:
  endPoint: http://oss-cn-beijing.aliyuncs.com
  bucketName: api-crap-cn
  imgPrefix: https://api-crap-cn.oss-cn-beijing.aliyuncs.com/
